S     = .
L     = 
X     = 
CC    = mpicc
F77   = mpif77
P     = -r8

FLAGS = -mcmodel=medium -O3

CFLAGS   = -c 
FFLAGS   = -c 

NOBJS = x2p.o comm_mpi.o

all: x2p


x2p:	$(NOBJS)
	$(F77) -o x2p $(NOBJS) $(FLAGS)

clean:
	'rm' *.o
	'rm' x2p


x2p.o   	: x2p.f 	; $(F77) -c $P $(FLAGS)  x2p.f 
comm_mpi.o   	: comm_mpi.f 	; $(F77) -c $P $(FLAGS)  comm_mpi.f 
